---
abstract: 'Apply HTTP content negotiation as Plack middleware'
author:
  - 'Jakob Voß <voss@gbv.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Negotiate
requires:
  HTTP::Negotiate: 6.01
  Log::Contextual: 0.006
  Plack: 1.0
  perl: v5.10.1
resources:
  bugtracker: https://github.com/nichtich/Plack-Middleware-Negotiate/issues
  homepage: https://github.com/nichtich/Plack-Middleware-Negotiate
  repository: https://github.com/nichtich/Plack-Middleware-Negotiate.git
version: 0.07
